### ISSUE TITLE
Y530 or Dell G7

### ISSUE THREAD

**Issue by kafran** [kfechter/LegionY530Ubuntu#21]
Hey guys, I'm thinking about to buy this laptop. I'm in doubt between the Lenovo Legion Y530 and the Dell G7. I'm buying it for work and as I'm a Linux user these issues made me be concerned about the Y530. Do you guys think the Dell G7 has a better Linux support? Are you regretted of Y530?

**Comment by kfechter** [comment]
I can't speak from experience, but looking at the specs of the Dell G7, since it has similar hardware the compatibility is most likely the same. maybe some of the quirks don't exist on the Dell, but I can't say for sure. The unit I have was sent for the purpose of review, but I don't have any regrets about the machine. The biggest problem with compatibility right now as far as I can tell is the fact that this hardware is new. It usually takes a couple of Ubuntu releases for the bugs to get ironed out.

**Comment by kfechter** [comment]
I can link the review later, however I did not include Linux as it was focused on the Gaming performance and features under windows. 

Issue #4 tracks programs for controlling fans and doing temp monitoring. The laptop seemed to control the fans normally on linux and on windows, so IMO the turbo fan isn't really needed.

**Comment by kfechter** [comment]
https://blog.kennethfechter.com/ 

my three part mini review of the Legion can be found at the above website. I will mark this issue as closed.
