### ISSUE TITLE
Unable to install ubuntu 18.10

### ISSUE THREAD

**Issue by slim-hmidi** [kfechter/LegionY530Ubuntu#25]
I followed the instruction mentioned in the article [Installing Ubuntu 18.xx on the Legion Y530](https://forums.lenovo.com/t5/Gaming-Laptops-Knowledge-Base/Installing-Ubuntu-18-xx-on-the-Legion-Y530/ta-p/4187251)

I followed ubuntu steps but when I arrived to installation tab I am not able to partition the table.
The only choice was `/dev/sdb` and the usb key was mounted under `/dev/sdb`. I tried multiple times to install ubuntu with windows 10 but I can't. How can I fix that?

**Comment by kfechter** [comment]
If you have an SSD equipped model, it may not show up as a /dev/sdX device.

PCIe SSDs will show as a  /dev/nvmeX device. If it's not detecting any diskdrives, then something may be misconfigured in the BIOS. Seems strange that it isn't detecting the installed OS if windows is booting correctly.

in the BIOS, what are your storage settings set to?

**Comment by slim-hmidi** [comment]
@kfechter sorry for the late but I found that in BIOS storage is RST mode.

**Comment by kfechter** [comment]
mine is in AHCI mode. the mode probably depends on what the machine was originally configured with. 

which storage options did your Legion come with? The model I have has a 256GB NVMe disk and a 1TB hard drive.

**Comment by slim-hmidi** [comment]
I don't know if it is an answer for your question or not : 
![ssd](https://user-images.githubusercontent.com/31925861/51792186-393f8100-21ae-11e9-90ed-e6591e8e8ab8.PNG)

**Comment by kfechter** [comment]
That works. Explains why RST mode is activated, and is most likely why Ubuntu isn't seeing any drives. It doesn't tell me the size of the optane drive, but looking at the configuration options on Lenovo's site, it's likely a 16GB module. Setting the storage mode to AHCI will probably allow Ubuntu to see the storage devices, however this will make Windows not boot. 

Optane is unfortunately not supported on Linux, so the accelerated hard drive scenario won't work under ubuntu.

That only leaves a few options. 

You can set the storage mode to AHCI, and install windows on the hard drive, then install ubuntu as a dual boot on the hard drive. Downside to this is the slower performance of the hard drive.

You can set the storage mode to AHCI and install windows on the hard drive and ubuntu on the optane module (which will function as a normal SSD). In this scenario, windows will take the performance hit being on the hard drive. Ubuntu will be fast, however unless you partition the hard drive or give storage from the hard drive to Ubuntu, ubuntu will be somewhat limited by the 16GB.

you can set the storage mode to AHCI, install ubuntu as the only OS on the optane module, and set the hard drive up as storage for the OS. Downside to this is you wouldn't have windows unless you run it in a VM. 

Last option is to replace the optane module with an ssd (either 250GB/256GB or 500GB/512GB), then set the storage mode to AHCI and install windows on the SSD, then install ubuntu in dual boot and use the 1TB hard drive as storage for one or both OSes

**Comment by slim-hmidi** [comment]
Thank you very much for this explanation.

**Comment by tommyalvarez** [comment]
@kfechter @slim-hmidi  That's not quite true. You can make it work without turning to AHCI. Although ubuntu won't get the performance boost of booting and caching of intel optane, it will be able to dual boot with windows still using it. I'd just installed it in my Lenovo Yoga 530 that comes with 16GB Intel Optane drive + 1TB SATA HDD and has a bios setup with UEFI and Storage mode Intel RST (Fake Raid as they call it). You can avoid changing it to AHCI and going through the windows safe boot trick to install ahci win drivers by doing the following:

-  Booting from the DVD/USB using the option _try ubuntu without install_
- Once in, open up a terminal and issue the following command which will Load the Intel Rapid Storage RAID driver in Linux for the drive you wish to install it, normally sda.

**sudo dmraid -E -r /dev/sda **

It may prompt if you want to delete some metadata version from it. I Just say yes, though i need more info on this. That's it. Now when you start the ubuntu installation from the desktop icon and reach the installation type step, it will read the HD disks and offer you the possibility of installing ubuntu alongside windows. No need to go to AHCI storage mode.

You then follow this guide steps as usual, maybe adding nomodeset to the grub menu if ubuntu freezes before login screen after install due to nvidia drivers issue that you solve later. 

Source of this is: https://davidvielmetter.com/tricks/installing-ubuntu-dual-boot-on-a-dell-precision-which-already-runs-windows-10/

Following Step 2.

**Comment by kfechter** [comment]
@tommyalvarez That's good to know. Thanks for the info. 

I've never had good experiences with fakeraid on linux, but I will add your information to the considerations section of the guide rewrite.
