### ISSUE TITLE
battery backup sucks , even on other distros!!

### ISSUE THREAD

**Issue by mrmtheboss** [kfechter/LegionY530Ubuntu#89]
I have tried many distros but this problem seems to be everywhere!
have you had this problem on your machine??
for note:
I have used tlp and powertop but none seem to work.

**Comment by kfechter** [comment]
Do you have nvidia-prime packages configured (i.e: can you run `prime-select query`) If so, are you in nvidia mode. 

However, regardless of whether or not optimus is configured, the battery life on the laptop isn't great. In my testing while I was reviewing the laptop The longest battery run time I got was about 3 hours and 6 minutes. With the GPU on and all CPU governor settings on max performance, I got 1 hour and 5 minutes. The biggest issue is the somewhat small battery they packed. Looks like some reviewers were able to get 4 hours and 44 minutes out of it, but I think that would be the high end, since again, its battery is smaller than most other gaming laptops

**Comment by mrmtheboss** [comment]
I think that's my issue,
Consider this, in my unit I am able to get like 4 hours easily on windows 10 chrome + atom that is just by undervolting -0.135 V.
And if I can get even 3 hours or so on ubuntu 20.04 or elementary is ..I will completely switch to linux..
I will try your solution and will edit this comment.
Thanks mate for the quick response!!!

**Comment by utajum** [comment]
You can also try https://github.com/georgewhewell/undervolt.git
Post back if it works

**Comment by mrmtheboss** [comment]
sure!

**Comment by mrmtheboss** [comment]
Found my answer!
